// Public document module surface; edits and queries share this entry point.
export { blockIsGridView, doc, formatForBlock, formatForPage, mainPages, pageByName, setDoc, setPageId } from "./model";
export type { FeedPage, Node } from "./model";
export { clearConflict, conflicts, flushAll, flushPage, forceSave, isConflicted, isDirty, isSaving, markConflict, markDirty, pageInstanceGeneration, scheduleSave, setConflicts, trackAssetWrite } from "./save/engine";
export { appendFeed, deletePage, emptyPage, ensurePageLoaded, forgetPage, isGuidePage, loadFeed, loadGuidePages, loadSingle, registerPaneRouteProvider, reloadDisposition, reloadHlsIfLoaded, reloadPage, resetStore, restoreTodayJournalInFeed } from "./workingSet";
export type { ReloadDisposition } from "./workingSet";
export { pageToDto, resolveGuideBlockRef, resolveGuidePageDto } from "./convert";
export { depthOf, nextVisible, pageVisibleOrder, prevVisible, trailingVisibleEmptyLeaf, visibleOrder } from "./tree";
export type { OutlineScope } from "./tree";
export { clearUndoHistory, historyPageOnlyMode, installHistoryRouteContextAdapter, invalidateUndoForPage, redo, toggleUndoRedoMode, undo, withUndoUnit } from "./history";
export type { HistoryRouteContext } from "./history";
export { deleteBlock, ensureEmptyBlock, indentBlock, insertEmptyChildBlock, insertOutlineAfter, insertOutlineChildren, mergeWithPrev, outdentBlock, replaceChildOrders, replaceEmptyBlockWithOutline, setCollapsed, setRaw, splitBlock, toggleCollapse } from "./edits/blocks";
export { pasteClipboardPayload } from "./edits/paste";
export { appendToTodayJournal, captureToPage } from "./edits/capture";
export { beginPageHeaderEdit, blockPageReadOnly, blockProperty, blockWritable, collapsibleDescendantIds, finishPageHeaderEdit, makeOwnNumberedList, orderedListMarker, pageWritable, promotePagePreamble, readPageProperty, readSchedule, removeOwnNumberedList, setBlockProperty, setCollapsedDeep, setCollapsedDescendants, setHeading, setPageProperty, setSchedule, stopOwnNumberedListOnEmptyEnter, toggleBlockProperty, toggleListItem, toggleListItemAtIndex, toggleOwnNumberedList } from "./edits/properties";
export type { HeadingState } from "./edits/properties";
export { blockExternalId, blockRef, ensureBlockId, ensureStableBlockId, existingBlockId, persistBlockRefTarget, persistentBlockRef, rawWithBlockId, resolveBlockRef } from "./edits/identity";
export type { LoadedBlockRef } from "./edits/identity";
export { blockSubtreeMarkdown, buildClipboardPayload, dtoSubtreeMarkdown, exportNodesFor } from "./edits/serialize";
export { clearSelection, cycleSelectionTasks, deleteSelection, extendSelectionTo, hasSelection, indentSelection, isSelected, moveSelection, outdentSelection, selectBlock, selectedIds, selectionMarkdown } from "./edits/selection";
export { extendFeedForScroll, isBlockMoving, moveBlock, moveBlockFeed, moveItem, moveSelectionItems, nextVisibleOrExtend, prepareCrossPageSources, setBlockMoving, setFeedExtender } from "./edits/moves";
export { carryUnfinished } from "./edits/carry";
