#!/usr/bin/env node
// Regenerate the vendored frontend parser (src/render/wasm/) from crates/lsdoc-wasm.
//
// Run via `npm run build:wasm`. Needs `wasm-pack` + the `wasm32-unknown-unknown`
// target (NOT needed to merely build/run Tine — only to regenerate after an lsdoc
// bump). See docs/wasm-parse-plan.md.
//
// Steps:
//   1. Read the lsdoc git tag from crates/tine-core/Cargo.toml (the single source
//      of truth) and from crates/lsdoc-wasm/Cargo.toml; REFUSE if they differ
//      (the stale-wasm / forgot-to-bump guard, plan §7D).
//   2. wasm-pack build --target web (release), LSDOC_TAG stamped in.
//   3. Base64-encode the .wasm into src/render/wasm/lsdoc_wasm_bytes.ts and copy
//      the wasm-bindgen JS glue + .d.ts. These committed files are what the app
//      and CI consume — no fetch, no wasm toolchain at app-build time.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, copyFileSync, mkdtempSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "render", "wasm");

function lsdocTag(cargoTomlRelPath) {
  const txt = readFileSync(join(root, cargoTomlRelPath), "utf8");
  const m = txt.match(/lsdoc\s*=\s*\{[^}]*\btag\s*=\s*"([^"]+)"/);
  if (!m) throw new Error(`could not find lsdoc tag in ${cargoTomlRelPath}`);
  return m[1];
}

const coreTag = lsdocTag("crates/tine-core/Cargo.toml");
const wrapTag = lsdocTag("crates/lsdoc-wasm/Cargo.toml");
if (coreTag !== wrapTag) {
  console.error(
    `\n  lsdoc pin mismatch (plan §7D guard):\n` +
      `    crates/tine-core/Cargo.toml  -> ${coreTag}\n` +
      `    crates/lsdoc-wasm/Cargo.toml -> ${wrapTag}\n` +
      `  Bump both to the same tag before regenerating the wasm.\n`,
  );
  process.exit(1);
}
console.log(`lsdoc pin: ${coreTag} (tine-core == lsdoc-wasm ✓)`);

const tmp = mkdtempSync(join(tmpdir(), "lsdoc-wasm-"));
console.log(`wasm-pack build → ${tmp}`);
execFileSync(
  "wasm-pack",
  ["build", "crates/lsdoc-wasm", "--target", "web", "--release", "--out-dir", tmp, "--out-name", "lsdoc_wasm"],
  { cwd: root, stdio: "inherit", env: { ...process.env, LSDOC_TAG: coreTag } },
);

mkdirSync(outDir, { recursive: true });

// 1) Base64-inline the wasm bytes (no fetch under Tauri custom-protocol).
const wasm = readFileSync(join(tmp, "lsdoc_wasm_bg.wasm"));
const b64 = wasm.toString("base64");
const bytesTs =
  `// GENERATED by scripts/build-wasm.mjs — DO NOT EDIT.\n` +
  `// lsdoc ${coreTag}; raw wasm ${wasm.length} bytes, base64 ${b64.length} chars.\n` +
  `// Base64-inlined so the parser loads with NO fetch (works under Tauri's custom\n` +
  `// protocol + offline). Regenerate via \`npm run build:wasm\`.\n` +
  `export const LSDOC_TAG = ${JSON.stringify(coreTag)};\n` +
  `export const WASM_B64 = ${JSON.stringify(b64)};\n`;
writeFileSync(join(outDir, "lsdoc_wasm_bytes.ts"), bytesTs);

// 2) Vendor the wasm-bindgen JS glue + its type defs. Neutralize the glue's
//    default-path branch: `new URL('lsdoc_wasm_bg.wasm', import.meta.url)` would
//    make Vite statically emit/resolve the raw .wasm at build time — but we vendor
//    base64 only (no raw .wasm) and ALWAYS pass bytes to init(), so that branch is
//    dead code. Replace it so Vite never sees the asset URL.
let glue = readFileSync(join(tmp, "lsdoc_wasm.js"), "utf8");
const defaultPath = "module_or_path = new URL('lsdoc_wasm_bg.wasm', import.meta.url);";
if (!glue.includes(defaultPath)) {
  throw new Error(
    "build-wasm: expected default-path line not found in glue — wasm-bindgen output " +
      "changed; re-check the Vite asset-URL neutralization in scripts/build-wasm.mjs.",
  );
}
glue = glue.replace(
  defaultPath,
  "throw new Error('lsdoc-wasm: init() must be called with explicit bytes (see src/render/parse.ts); default fetch path is disabled.');",
);
writeFileSync(join(outDir, "lsdoc_wasm.js"), glue);
copyFileSync(join(tmp, "lsdoc_wasm.d.ts"), join(outDir, "lsdoc_wasm.d.ts"));

console.log(
  `vendored → src/render/wasm/ (lsdoc_wasm.js, lsdoc_wasm.d.ts, lsdoc_wasm_bytes.ts; ` +
    `${(wasm.length / 1024).toFixed(0)} KB wasm → ${(b64.length / 1024).toFixed(0)} KB base64)`,
);
